contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    # contact
    path('<int:contact_id>/', views.contact, name='contact'),
    path('<int:contact_id>/update/', views.update, name='update'),
    path('<int:contact_id>/delete/', views.delete, name='delete'),
    path('create', views.create, name='create'),
    path('search', views.search, name='search'),
    path('', views.index, name='index'),
    # user
    path('user/register', views.register, name='register'),
    path('user/login', views.login_view, name='login'),
    path('user/logout', views.logout, name='logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from uuid import uuid4
# Create your models here.


class Category(models.Model):

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=255, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to=f'pictures/{uuid4()}')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, blank=True, null=True)
    owner = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ContactForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'somente primeiro nome',
            }
        ),
        label='Nome',
    )

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'sobrenome completo',
            }
        ),
        label='Sobrenome',
    )

    phone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'telefone',
            }
        ),
        label='Telefone',
        help_text='somente números'
    )

    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'email'
            }
        ),
        label='E-mail'
    )

    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'rows': '10',
            }
        ),
        label='Descrição'
    )

    picture = forms.ImageField(
        widget=forms.FileInput(attrs={'accept': 'image/*'}))

    class Meta:
        model = models.Contact
        fields = ('first_name', 'last_name', 'phone', 'email',
                  'description', 'category', 'picture')

    def clean(self):
        # cleaned_data = self.cleaned_data

        # self.add_error(
        #     'first_name',
        #     ValidationError(
        #         'Mensagem de erro',
        #         code='invalid'
        #     )
        # )
        # self.add_error(
        #     'first_name',
        #     ValidationError(
        #         'Mensagem de erro 2',
        #         code='invalid'
        #     )
        # )

        return super().clean()


class RegisterForm(UserCreationForm):
    ...

    first_name = forms.CharField(required=True, label='Nome')
    last_name = forms.CharField(required=True, label='Sobrenome')
    email = forms.EmailField(label='E-mail')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',
                  'username', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            self.add_error('email', ValidationError(
                'E-mail já existe', code='invalid'))
        return email

contact/views/forms.py
from django.shortcuts import render, redirect, get_object_or_404
from contact.forms import ContactForm
from contact.models import Contact
from django.urls import reverse


def create(request):
    form_action = reverse('contact:create')

    context = {
        'form': ContactForm(),
        'form_action': form_action
    }

    if request.method == 'POST':

        form = ContactForm(request.POST, request.FILES)
        context['form'] = form

        if form.is_valid():
            contact = form.save()
            return redirect('contact:index')

    return render(request, 'contact/create.html', context)


def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True)

    form_action = reverse('contact:update', args=(contact_id,))

    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action
    }

    if request.method == 'POST':

        form = ContactForm(request.POST, request.FILES, instance=contact)
        context['form'] = form

        if form.is_valid():
            c = form.save()
            return redirect('contact:contact', contact_id=c.pk)

    return render(request, 'contact/create.html', context)


def delete(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True)
    confirm = request.POST.get('confirm', 'no')

    if confirm == 'yes':
        contact.delete()
        return redirect('contact:index')

    context = {'contact': contact, 'confirm': confirm}

    return render(request, 'contact/contact.html', context)

contact/views.py
from django.shortcuts import render

def index(request):
    return render(
        request,
        'contact/index.html',
    )

contact/views/contact_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from contact.forms import ContactForm
from contact.models import Contact
from django.urls import reverse


def create(request):
    form_action = reverse('contact:create')

    context = {
        'form': ContactForm(),
        'form_action': form_action
    }

    if request.method == 'POST':

        form = ContactForm(request.POST, request.FILES)
        context['form'] = form

        if form.is_valid():
            contact = form.save()
            return redirect('contact:index')

    return render(request, 'contact/create.html', context)


def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True)

    form_action = reverse('contact:update', args=(contact_id,))

    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action
    }

    if request.method == 'POST':

        form = ContactForm(request.POST, request.FILES, instance=contact)
        context['form'] = form

        if form.is_valid():
            c = form.save()
            return redirect('contact:contact', contact_id=c.pk)

    return render(request, 'contact/create.html', context)


def delete(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True)
    confirm = request.POST.get('confirm', 'no')

    if confirm == 'yes':
        contact.delete()
        return redirect('contact:index')

    context = {'contact': contact, 'confirm': confirm}

    return render(request, 'contact/contact.html', context)

contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect
from contact.models import Contact
from django.db.models import Q
from django.core.paginator import Paginator


def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj, 'title': 'Contatos'}
    return render(request, 'contact/index.html', context)


def contact(request, contact_id):
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)
    context = {'contact': single_contact,
               'title': f'{single_contact.first_name} {single_contact.last_name}'}
    return render(request, 'contact/contact.html', context)


def search(request):
    search_value = request.GET.get('q', '').strip()
    if not search_value:
        return redirect('contact:index')
    contacts = Contact.objects.filter(
        Q(first_name__icontains=search_value) |
        Q(last_name__icontains=search_value) |
        Q(phone__icontains=search_value) |
        Q(email__icontains=search_value),
        show=True
    ).order_by('id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj, 'title': 'Contatos',
               'search_value': search_value, 'url_search': f'&q={search_value}'}
    return render(request, 'contact/index.html', context)

contact/views/index.py
from django.shortcuts import render, get_object_or_404, redirect
from contact.models import Contact
from django.db.models import Q
from django.core.paginator import Paginator


def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj, 'title': 'Contatos'}
    return render(request, 'contact/index.html', context)


def contact(request, contact_id):
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)
    context = {'contact': single_contact,
               'title': f'{single_contact.first_name} {single_contact.last_name}'}
    return render(request, 'contact/contact.html', context)


def search(request):
    search_value = request.GET.get('q', '').strip()
    if not search_value:
        return redirect('contact:index')
    contacts = Contact.objects.filter(
        Q(first_name__icontains=search_value) |
        Q(last_name__icontains=search_value) |
        Q(phone__icontains=search_value) |
        Q(email__icontains=search_value),
        show=True
    ).order_by('id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj, 'title': 'Contatos',
               'search_value': search_value, 'url_search': f'&q={search_value}'}
    return render(request, 'contact/index.html', context)

contact/views/user_forms.py
from django.shortcuts import render, redirect
from contact.forms import RegisterForm
from django.urls import reverse
from django.contrib import messages, auth
from django.contrib.auth.forms import AuthenticationForm


def register(request):

    form = RegisterForm()
    form_action = reverse('contact:register')

    if request.method == 'POST':

        form = RegisterForm(request.POST)

        if form.is_valid():
            contact = form.save()
            messages.success(request, 'Usuário registrado')
            return redirect('contact:index')

    return render(
        request,
        'contact/register.html',
        {
            'form': form,
            'form_action': form_action
        }
    )


def login_view(request):

    form = AuthenticationForm(request)
    form_action = reverse('contact:login')

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('contact:login')

    return render(
        request,
        'contact/login.html',
        {
            'form': form,
            'form_action': form_action
        }
    )


def logout(request):
    auth.logout(request)
    return redirect('contact:login')

contact/templates/contact/contact.html
{% extends 'global/base.html' %} {% block content %}
<div class="single-contact">
  <h1 class="single-contact-name">
    {{ contact.first_name }} {{ contact.last_name }}
  </h1>

  {% if contact.picture %}
  <img
    src="{{ contact.picture.url }}"
    alt="image_{{ contact.first_name }}_{{ contact.last_name }}"
    height="200"
  />
  {% endif %}

  <p><b>ID:</b> {{ contact.id }}</p>
  <p><b>E-mail:</b> {{ contact.email }}</p>
  <p><b>Phone:</b> {{ contact.phone }}</p>
  <p><b>Created Date:</b> {{ contact.created_date }}</p>
  <p><b>Description:</b> {{ contact.description }}</p>
  <p><b>Category:</b> {{ contact.category.name }}</p>

  <div class="contact-links">
    <a class="btn btn-link" href="{% url 'contact:update' contact.id %}"
      >editar</a
    >
    <form action="{% url 'contact:delete' contact.id %}" method="POST">
      {% csrf_token %} {% if confirm == 'no' %}
      <input type="hidden" name="confirm" value="yes" />
      <button type="submit" class="btn btn-link btn-delete">confirma?</button>
      {% else %}
      <button type="submit" class="btn btn-link btn-delete">deletar</button>
      {% endif %}
    </form>
  </div>
</div>
{% endblock content %}

contact/templates/contact/create.html
{% extends 'global/base.html' %} {% block content %}
<div class="form-wrapper">
  <h1>create contact</h1>
  <form action="{{ form_action }}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-content">
      {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }} {{ field.errors }} {% if field.help_text %}
        <p class="help-text">{{ field.help_text }}</p>
        {% endif %} {% if field.name == 'picture' and field.value.url %}
        <img
          src="{{field.value.url}}"
          alt="{{ field.name }}"
          height="auto"
          width="50%"
        />
        {% endif %}
      </div>
      {% endfor %}
    </div>

    {% if form.non_field_errors %}
    <div class="form-content">
      <div class="form-group">
        <div class="message error">{{ form.non_field_errors }}</div>
      </div>
    </div>
    {% endif %}

    <div class="form-content">
      <div class="form-group">
        <button class="btn" type="submit">Send</button>
      </div>
    </div>
  </form>
</div>
{% endblock content %}

contact/templates/contact/index.html
{% extends 'global/base.html' %} {% block content %} {% if page_obj %}
<div class="responsive-table">
  <table class="contacts-table">
    <caption class="table-caption">
      Contacts
    </caption>

    <thead>
      <tr class="table-row table-row-header">
        <th class="table-header">Name</th>
        <th class="table-header">Phone</th>
        <th class="table-header">E-mail</th>
      </tr>
    </thead>

    <tbody>
      {% for contact in page_obj %}
      <tr class="table-row">
        <td class="table-cel">
          <a class="table-link" href="{% url 'contact:contact' contact.id %}">
            {{ contact.first_name }} {{ contact.last_name }}
          </a>
        </td>
        <td class="table-cel">{{ contact.phone }}</td>
        <td class="table-cel">{{ contact.email }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<div class="single-contact">
  <h3 class="single-contact-name">Nenhum contato encontrado</h3>
</div>
{% endif %} {% endblock content %}

contact/templates/contact/login.html
{% extends 'global/base.html' %} {% block content %}
<div class="form-wrapper">
  <h1>Login</h1>

  {% if user.is_authenticated %}
    <p>Olá {{ user }}, clique <a href="{% url 'contact:logout' %}">aqui</a> para sair</p>
  {% else %}
    {% include 'contact/partials/_user-form.html' %}
  {% endif %}


</div>
{% endblock content %}

contact/templates/contact/register.html
{% extends 'global/base.html' %} {% block content %}
<div class="form-wrapper">
  <h1>Register user</h1>

  {% include 'contact/partials/_user-form.html' %}

</div>
{% endblock content %}